# Generated by Django 3.2 on 2021-05-16 06:54

from django.db import migrations
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('App_Blog', '0003_auto_20210513_0858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='header_image',
            field=image_optimizer.fields.OptimizedImageField(upload_to='header_images'),
        ),
    ]
